services:
  generator:
    build:
      context: .
      dockerfile: Dockerfile.generator
    volumes:
      - ./data_generator.py:/app/data_generator.py
      - ./requirements.txt:/app/requirements.txt
    networks:
      - app-network
    depends_on:
      - redis
    command: python /app/data_generator.py

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    volumes:
      - ./worker.py:/app/worker.py
      - ./requirements.txt:/app/requirements.txt
    depends_on:
      - generator
      - influxdb
      - redis
    networks:
      - app-network
    environment:
      - REDIS_HOST=redis
      - INFLUXDB_HOST=influxdb
      - INFLUXDB_TOKEN=h4TtaKhm5jxL4i0YjegFKSyZn0s0jgZakQ3TJB97FxiQIho_K1-Ae08oS4-BUpLd7hp4wAH0vULt3KUAA70T-w==
    command: python /app/worker.py

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    volumes:
      - ./dashboard.py:/app/dashboard.py
      - ./requirements.txt:/app/requirements.txt
    ports:
      - "8050:8050"
    depends_on:
      - worker
    networks:
      - app-network
    command: python /app/dashboard.py

  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    networks:
      - app-network
    volumes:
      - redis-data:/data

  influxdb:
    image: influxdb:2.7
    ports:
      - "8086:8086"
    volumes:
      - influxdb-storage:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpassword
      - DOCKER_INFLUXDB_INIT_ORG=myorg
      - DOCKER_INFLUXDB_INIT_BUCKET=color_data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  influxdb-storage:
  redis-data: